export const COMPANIONS = {
  fox: {
    id: 'fox',
    name: 'Shadow Fox',
    icon: '🦊',
    textureKey: 'companion_fox',
    description: 'A sleek fox drawn to valuable loot.',
    perk: {
      id: 'lucky_hunter',
      name: 'Lucky Hunter',
      description: '+15% rare loot drop chance from all mobs.',
      effect: { rareLootBonus: 0.15 },
    },
    acquisition: {
      source: 'nocturnal_mob_drop',
      mob: 'ember_wraith',
      dropRate: 0.02,
      egg: 'companion_egg_fox',
    },
    followDistance: 1.5,
    idleAnimation: 'sit',
    moveSpeed: 1.1,
    size: { w: 12, h: 10 },
  },
  owl: {
    id: 'owl',
    name: 'Moon Owl',
    icon: '🦉',
    textureKey: 'companion_owl',
    description: 'A silent owl that sees through the night.',
    perk: {
      id: 'night_sight',
      name: 'Night Sight',
      description: 'Night fog opacity reduced by 40%. Night mob positions visible on approach.',
      effect: { nightFogReduction: 0.40, nightMobRevealRange: 5 },
    },
    acquisition: {
      source: 'nocturnal_mob_drop',
      mob: 'shadow_wisp',
      dropRate: 0.02,
      egg: 'companion_egg_owl',
    },
    followDistance: 0,
    idleAnimation: 'perch',
    moveSpeed: 1.3,
    size: { w: 10, h: 10 },
  },
  frog: {
    id: 'frog',
    name: 'Tidecaller Frog',
    icon: '🐸',
    textureKey: 'companion_frog',
    description: 'A plump frog that brings luck to anglers.',
    perk: {
      id: 'anglers_luck',
      name: "Angler's Luck",
      description: '+20% fishing catch chance. +10% double catch chance.',
      effect: { fishingCatchBonus: 0.20, fishingDoubleBonus: 0.10 },
    },
    acquisition: {
      source: 'fishing_rare_catch',
      pool: 'abyssal',
      catchRate: 0.03,
      egg: 'companion_egg_frog',
    },
    followDistance: 1.2,
    idleAnimation: 'hop',
    moveSpeed: 0.9,
    size: { w: 10, h: 8 },
  },
  mole: {
    id: 'mole',
    name: 'Gemclaw Mole',
    icon: '🐹',
    textureKey: 'companion_mole',
    description: 'A burrowing mole with a nose for precious ores.',
    perk: {
      id: 'ore_sense',
      name: 'Ore Sense',
      description: '+25% mining extract chance. Depleted nodes respawn 20% faster.',
      effect: { miningExtractBonus: 0.25, nodeRespawnBonus: 0.20 },
    },
    acquisition: {
      source: 'nocturnal_mob_drop',
      mob: 'moon_beetle',
      dropRate: 0.02,
      egg: 'companion_egg_mole',
    },
    followDistance: 1.0,
    idleAnimation: 'dig',
    moveSpeed: 0.8,
    size: { w: 10, h: 8 },
  },
  wolf: {
    id: 'wolf',
    name: 'Dusk Wolf',
    icon: '🐺',
    textureKey: 'companion_wolf',
    description: 'A fierce wolf that fights alongside you in spirit.',
    perk: {
      id: 'pack_hunter',
      name: 'Pack Hunter',
      description: '+10% damage dealt. -5% damage taken.',
      effect: { damageBonus: 0.10, damageReduction: 0.05 },
    },
    acquisition: {
      source: 'nocturnal_mob_drop',
      mob: 'night_stalker',
      dropRate: 0.02,
      egg: 'companion_egg_wolf',
    },
    followDistance: 1.8,
    idleAnimation: 'sit_alert',
    moveSpeed: 1.2,
    size: { w: 14, h: 12 },
  },
  toad: {
    id: 'toad',
    name: 'Grove Toad',
    icon: '🐊',
    textureKey: 'companion_toad',
    description: 'A plump toad that makes gardens flourish.',
    perk: {
      id: 'green_thumb',
      name: 'Green Thumb',
      description: '+20% crop growth speed. +15% bonus crop harvest chance.',
      effect: { farmGrowthBonus: 0.20, farmBonusCropBonus: 0.15 },
    },
    acquisition: {
      source: 'farming_rare_harvest',
      crop: 'moonberry',
      harvestRate: 0.04,
      egg: 'companion_egg_toad',
    },
    followDistance: 1.0,
    idleAnimation: 'croak',
    moveSpeed: 0.7,
    size: { w: 10, h: 8 },
  },
};

export const EGG_HATCH_CONFIG = {
  hatchDuration: 60000,
  nestPosition: { tileX: 12, tileY: 35 },
  textureKey: 'tile_companion_nest',
  maxEggsAtOnce: 1,
};
