export const SEEDS = {
  wheat_seed: {
    id: 'wheat_seed',
    name: 'Wheat Seed',
    icon: '🌾',
    textureKey: 'seed_wheat',
    cost: 5,
    requiredFarmingLevel: 1,
    growthTime: 30000,
    crop: 'wheat',
    cropYield: { min: 1, max: 2 },
  },
  carrot_seed: {
    id: 'carrot_seed',
    name: 'Carrot Seed',
    icon: '🥕',
    textureKey: 'seed_carrot',
    cost: 5,
    requiredFarmingLevel: 1,
    growthTime: 25000,
    crop: 'carrot',
    cropYield: { min: 1, max: 2 },
  },
  tomato_seed: {
    id: 'tomato_seed',
    name: 'Tomato Seed',
    icon: '🍅',
    textureKey: 'seed_tomato',
    cost: 10,
    requiredFarmingLevel: 2,
    growthTime: 45000,
    crop: 'tomato',
    cropYield: { min: 1, max: 3 },
  },
  golden_wheat_seed: {
    id: 'golden_wheat_seed',
    name: 'Golden Wheat Seed',
    icon: '✨',
    textureKey: 'seed_golden_wheat',
    cost: 25,
    requiredFarmingLevel: 4,
    growthTime: 60000,
    crop: 'golden_wheat',
    cropYield: { min: 1, max: 2 },
  },
  moonberry_seed: {
    id: 'moonberry_seed',
    name: 'Moonberry Seed',
    icon: '🫐',
    textureKey: 'seed_moonberry',
    cost: 40,
    requiredFarmingLevel: 6,
    growthTime: 90000,
    crop: 'moonberry',
    cropYield: { min: 1, max: 2 },
  },
  starfruit_seed: {
    id: 'starfruit_seed',
    name: 'Starfruit Seed',
    icon: '⭐',
    textureKey: 'seed_starfruit',
    cost: 60,
    requiredFarmingLevel: 8,
    growthTime: 120000,
    crop: 'starfruit',
    cropYield: { min: 1, max: 1 },
  },
  mystery_seed: {
    id: 'mystery_seed',
    name: 'Mystery Seed',
    icon: '🌱',
    textureKey: 'seed_mystery',
    cost: 30,
    requiredFarmingLevel: 1,
    growthTime: 45000,
    crop: 'mystery',
    cropYield: { min: 1, max: 3 },
    shopAvailable: false,
  },
  ember_pepper_seed: {
    id: 'ember_pepper_seed',
    name: 'Ember Pepper Seed',
    icon: '🌶️',
    textureKey: 'seed_ember_pepper',
    cost: 45,
    requiredFarmingLevel: 3,
    growthTime: 60000,
    crop: 'ember_pepper',
    cropYield: { min: 1, max: 2 },
    shopAvailable: false,
  },
  frost_lily_seed: {
    id: 'frost_lily_seed',
    name: 'Frost Lily Seed',
    icon: '❄️',
    textureKey: 'seed_frost_lily',
    cost: 50,
    requiredFarmingLevel: 4,
    growthTime: 90000,
    crop: 'frost_lily',
    cropYield: { min: 1, max: 1 },
    shopAvailable: false,
  },
};

export const CROPS = {
  wheat:        { id: 'wheat',        name: 'Wheat',        icon: '🌾', sellValue: 4,  category: 'crop' },
  carrot:       { id: 'carrot',       name: 'Carrot',       icon: '🥕', sellValue: 4,  category: 'crop' },
  tomato:       { id: 'tomato',       name: 'Tomato',       icon: '🍅', sellValue: 7,  category: 'crop' },
  golden_wheat: { id: 'golden_wheat', name: 'Golden Wheat', icon: '✨', sellValue: 15, category: 'crop' },
  moonberry:    { id: 'moonberry',    name: 'Moonberry',    icon: '🫐', sellValue: 22, category: 'crop' },
  starfruit:    { id: 'starfruit',    name: 'Starfruit',    icon: '⭐', sellValue: 40, category: 'crop' },
  ember_pepper: { id: 'ember_pepper', name: 'Ember Pepper', icon: '🌶️', sellValue: 28, category: 'crop' },
  frost_lily:   { id: 'frost_lily',   name: 'Frost Lily',   icon: '❄️', sellValue: 35, category: 'crop' },
};
