export const ITEMS = {
  slimeGel: { id: 'slimeGel', name: 'Slime Gel', emoji: '💚', sellValue: 2 },
  wolfPelt: { id: 'wolfPelt', name: 'Wolf Pelt', emoji: '🟤', sellValue: 5 },
  fang: { id: 'fang', name: 'Fang', emoji: '🦷', sellValue: 3 },
  batWing: { id: 'batWing', name: 'Bat Wing', emoji: '🖤', sellValue: 4 },
  echoStone: { id: 'echoStone', name: 'Echo Stone', emoji: '💎', sellValue: 10 },
  goldCoin: { id: 'goldCoin', name: 'Gold Coin', emoji: '🪙', sellValue: 0 },
  // Fish
  small_fish: { id: 'small_fish', name: 'Small Fish', emoji: '🐟', sellValue: 3, category: 'fish' },
  large_fish: { id: 'large_fish', name: 'Large Fish', emoji: '🐠', sellValue: 7, category: 'fish' },
  river_crab: { id: 'river_crab', name: 'River Crab', emoji: '🦀', sellValue: 5, category: 'fish' },
  golden_carp: { id: 'golden_carp', name: 'Golden Carp', emoji: '✨', sellValue: 15, category: 'fish' },
  abyssal_eel: { id: 'abyssal_eel', name: 'Abyssal Eel', emoji: '🐍', sellValue: 12, category: 'fish' },
  old_boot: { id: 'old_boot', name: 'Old Boot', emoji: '👢', sellValue: 1, category: 'junk' },
  pearl_fragment: { id: 'pearl_fragment', name: 'Pearl Fragment', emoji: '🤍', sellValue: 8, category: 'gem' },
  crystal_shell: { id: 'crystal_shell', name: 'Crystal Shell', emoji: '🐚', sellValue: 10, category: 'gem' },
  sea_gem: { id: 'sea_gem', name: 'Sea Gem', emoji: '💠', sellValue: 20, category: 'gem' },
  ancient_coin: { id: 'ancient_coin', name: 'Ancient Coin', emoji: '🪙', sellValue: 0, category: 'special', goldValue: 25 },
  sunken_ring: { id: 'sunken_ring', name: 'Sunken Ring', emoji: '💍', sellValue: 18, category: 'gem' },
  // Ores
  copper_ore: { id: 'copper_ore', name: 'Copper Ore', emoji: '🟠', sellValue: 4, category: 'ore' },
  iron_ore: { id: 'iron_ore', name: 'Iron Ore', emoji: '⬜', sellValue: 8, category: 'ore' },
  crystal_ore: { id: 'crystal_ore', name: 'Crystal Ore', emoji: '🔷', sellValue: 14, category: 'ore' },
  rough_stone: { id: 'rough_stone', name: 'Rough Stone', emoji: '🪨', sellValue: 2, category: 'ore' },
  copper_nugget: { id: 'copper_nugget', name: 'Copper Nugget', emoji: '🟤', sellValue: 10, category: 'ore' },
  iron_nugget: { id: 'iron_nugget', name: 'Iron Nugget', emoji: '⚪', sellValue: 16, category: 'ore' },
  gemstone_shard: { id: 'gemstone_shard', name: 'Gemstone Shard', emoji: '💎', sellValue: 12, category: 'gem' },
  void_crystal: { id: 'void_crystal', name: 'Void Crystal', emoji: '🟣', sellValue: 25, category: 'gem' },
  // Seeds
  wheat_seed:        { id: 'wheat_seed',        name: 'Wheat Seed',        emoji: '🌾', sellValue: 2,  category: 'seed' },
  carrot_seed:       { id: 'carrot_seed',        name: 'Carrot Seed',       emoji: '🥕', sellValue: 2,  category: 'seed' },
  tomato_seed:       { id: 'tomato_seed',        name: 'Tomato Seed',       emoji: '🍅', sellValue: 4,  category: 'seed' },
  golden_wheat_seed: { id: 'golden_wheat_seed',  name: 'Golden Wheat Seed', emoji: '✨', sellValue: 10, category: 'seed' },
  moonberry_seed:    { id: 'moonberry_seed',     name: 'Moonberry Seed',    emoji: '🫐', sellValue: 15, category: 'seed' },
  starfruit_seed:    { id: 'starfruit_seed',     name: 'Starfruit Seed',    emoji: '⭐', sellValue: 20, category: 'seed' },
  // Crops
  wheat:        { id: 'wheat',        name: 'Wheat',        emoji: '🌾', sellValue: 4,  category: 'crop' },
  carrot:       { id: 'carrot',       name: 'Carrot',       emoji: '🥕', sellValue: 4,  category: 'crop' },
  tomato:       { id: 'tomato',       name: 'Tomato',       emoji: '🍅', sellValue: 7,  category: 'crop' },
  golden_wheat: { id: 'golden_wheat', name: 'Golden Wheat', emoji: '✨', sellValue: 15, category: 'crop' },
  moonberry:    { id: 'moonberry',    name: 'Moonberry',    emoji: '🫐', sellValue: 22, category: 'crop' },
  starfruit:    { id: 'starfruit',    name: 'Starfruit',    emoji: '⭐', sellValue: 40, category: 'crop' },
  // Food (consumables)
  basic_stew:      { id: 'basic_stew',      name: 'Basic Stew',      emoji: '🍲', sellValue: 8,  category: 'food', duration: 60000,  buff: { stats: { atk: 3 } } },
  carrot_soup:     { id: 'carrot_soup',     name: 'Carrot Soup',     emoji: '🥣', sellValue: 8,  category: 'food', duration: 60000,  buff: { stats: { def: 3 } } },
  grilled_fish:    { id: 'grilled_fish',    name: 'Grilled Fish',    emoji: '🐟', sellValue: 10, category: 'food', duration: 60000,  buff: { stats: { maxHp: 15 }, heal: 15 } },
  hearty_chowder:  { id: 'hearty_chowder',  name: 'Hearty Chowder',  emoji: '🍲', sellValue: 15, category: 'food', duration: 90000,  buff: { stats: { atk: 4, def: 4 } } },
  miners_meal:     { id: 'miners_meal',     name: "Miner's Meal",    emoji: '🍽', sellValue: 15, category: 'food', duration: 90000,  buff: { skillEffects: { mining: { cycleSpeedBonus: 0.30, extractChanceBonus: 0.30 } } } },
  golden_bread:    { id: 'golden_bread',    name: 'Golden Bread',    emoji: '🍞', sellValue: 22, category: 'food', duration: 120000, buff: { stats: { atk: 6, def: 3, maxHp: 10 } } },
  anglers_feast:   { id: 'anglers_feast',   name: "Angler's Feast",  emoji: '🐟', sellValue: 22, category: 'food', duration: 120000, buff: { skillEffects: { fishing: { cycleSpeedBonus: 0.30, catchChanceBonus: 0.30, doubleCatchBonus: 0.15 } } } },
  moonberry_tart:  { id: 'moonberry_tart',  name: 'Moonberry Tart',  emoji: '🥧', sellValue: 30, category: 'food', duration: 120000, buff: { stats: { atk: 8, def: 5, maxHp: 20 } } },
  abyssal_broth:   { id: 'abyssal_broth',   name: 'Abyssal Broth',   emoji: '🍵', sellValue: 30, category: 'food', duration: 120000, buff: { stats: { atk: 10 }, skillEffects: { farming: { growthSpeedBonus: 0.25 } } } },
  starfruit_elixir:{ id: 'starfruit_elixir',name: 'Starfruit Elixir',emoji: '🧪', sellValue: 50, category: 'food', duration: 180000, buff: { stats: { atk: 12, def: 8, maxHp: 30 }, skillEffects: { fishing: { cycleSpeedBonus: 0.15 }, mining: { cycleSpeedBonus: 0.15 }, farming: { growthSpeedBonus: 0.15 } } } },
  // === Phase 5: Swamp & Volcanic Materials ===
  bog_moss:     { id: 'bog_moss',     name: 'Bog Moss',     emoji: '🌿', sellValue: 8,  category: 'material' },
  witch_eye:    { id: 'witch_eye',    name: 'Witch Eye',    emoji: '👁️', sellValue: 12, category: 'material' },
  lava_rock:    { id: 'lava_rock',    name: 'Lava Rock',    emoji: '🪨',  sellValue: 10, category: 'material' },
  ash_dust:     { id: 'ash_dust',     name: 'Ash Dust',     emoji: '💨', sellValue: 6,  category: 'material' },
  forge_ember:  { id: 'forge_ember',  name: 'Forge Ember',  emoji: '🔥', sellValue: 20, category: 'material' },
  // === Phase 7: Night Materials ===
  shadow_essence:      { id: 'shadow_essence',      name: 'Shadow Essence',      emoji: '🌑', sellValue: 6,  category: 'material' },
  wisp_core:           { id: 'wisp_core',           name: 'Wisp Core',           emoji: '💠', sellValue: 14, category: 'material' },
  stalker_fang:        { id: 'stalker_fang',        name: 'Stalker Fang',        emoji: '🦷', sellValue: 12, category: 'material' },
  midnight_dew:        { id: 'midnight_dew',        name: 'Midnight Dew',        emoji: '💧', sellValue: 8,  category: 'material' },
  moonshell_fragment:  { id: 'moonshell_fragment',  name: 'Moonshell Fragment',  emoji: '🐚', sellValue: 10, category: 'material' },
  luminous_chitin:     { id: 'luminous_chitin',     name: 'Luminous Chitin',     emoji: '✨', sellValue: 16, category: 'material' },
  wraith_ember:        { id: 'wraith_ember',        name: 'Wraith Ember',        emoji: '🔥', sellValue: 18, category: 'material' },
  infernal_dust:       { id: 'infernal_dust',       name: 'Infernal Dust',       emoji: '💨', sellValue: 14, category: 'material' },
  // Companion Eggs (not sellable)
  companion_egg_fox:   { id: 'companion_egg_fox',   name: 'Fox Egg',   emoji: '🥚', sellValue: 0, category: 'companion_egg' },
  companion_egg_owl:   { id: 'companion_egg_owl',   name: 'Owl Egg',   emoji: '🥚', sellValue: 0, category: 'companion_egg' },
  companion_egg_frog:  { id: 'companion_egg_frog',  name: 'Frog Egg',  emoji: '🥚', sellValue: 0, category: 'companion_egg' },
  companion_egg_mole:  { id: 'companion_egg_mole',  name: 'Mole Egg',  emoji: '🥚', sellValue: 0, category: 'companion_egg' },
  companion_egg_wolf:  { id: 'companion_egg_wolf',  name: 'Wolf Egg',  emoji: '🥚', sellValue: 0, category: 'companion_egg' },
  companion_egg_toad:  { id: 'companion_egg_toad',  name: 'Toad Egg',  emoji: '🥚', sellValue: 0, category: 'companion_egg' },
  // Merchant items
  merchant_mystery_seed: { id: 'merchant_mystery_seed', name: 'Mystery Seed',    emoji: '🌱', sellValue: 15, category: 'seed' },
  golden_treat:          { id: 'golden_treat',          name: 'Golden Treat',     emoji: '🦴', sellValue: 20, category: 'companion' },
  merchants_tonic:       { id: 'merchants_tonic',       name: "Merchant's Tonic", emoji: '🧴', sellValue: 18, category: 'food', duration: 120000, buff: { stats: {}, skillEffects: { sellValueBonus: 0.50 } } },
  wanderers_brew:        { id: 'wanderers_brew',        name: "Wanderer's Brew",  emoji: '🍶', sellValue: 25, category: 'food', duration: 180000, buff: { stats: {}, skillEffects: { moveSpeedBonus: 0.20 } } },
  scouts_map:            { id: 'scouts_map',            name: "Scout's Map",      emoji: '🗺️', sellValue: 30, category: 'consumable' },
  agent_morale_scroll:   { id: 'agent_morale_scroll',   name: 'Morale Scroll',   emoji: '📜', sellValue: 12, category: 'consumable' },
  stardust:              { id: 'stardust',              name: 'Stardust',         emoji: '✨', sellValue: 50, category: 'material' },
  exotic_feast:          { id: 'exotic_feast',          name: 'Exotic Feast',     emoji: '🍱', sellValue: 40, category: 'food', duration: 180000, buff: { stats: { atk: 10, def: 10, maxHp: 25 }, skillEffects: {} } },
  // Night fish
  moonfish:              { id: 'moonfish',     name: 'Moonfish',     emoji: '🐟', sellValue: 15, category: 'fish' },
  shadowfin:             { id: 'shadowfin',    name: 'Shadowfin',    emoji: '🐠', sellValue: 25, category: 'fish' },
  // Night crops
  ember_pepper:          { id: 'ember_pepper', name: 'Ember Pepper', emoji: '🌶️', sellValue: 28, category: 'crop' },
  frost_lily:            { id: 'frost_lily',   name: 'Frost Lily',   emoji: '❄️', sellValue: 35, category: 'crop' },
  // Night cooking
  midnight_broth:        { id: 'midnight_broth', name: 'Midnight Broth', emoji: '🍲', sellValue: 20, category: 'food', duration: 120000, buff: { stats: { atk: 5 }, skillEffects: { nightMobXpBonus: 0.20 } } },
  shadow_stew:           { id: 'shadow_stew',   name: 'Shadow Stew',   emoji: '🍲', sellValue: 30, category: 'food', duration: 90000,  buff: { stats: { atk: 8, def: 8 }, skillEffects: {} } },
  // Merchant-exclusive cooking
  inferno_stew:          { id: 'inferno_stew',   name: 'Inferno Stew',    emoji: '🔥', sellValue: 25, category: 'food', duration: 90000,  buff: { stats: { atk: 15 }, skillEffects: {} } },
  frostguard_soup:       { id: 'frostguard_soup', name: 'Frostguard Soup', emoji: '❄️', sellValue: 25, category: 'food', duration: 90000,  buff: { stats: { def: 15 }, skillEffects: {} } },
};
