export const ITEMS = {
  slimeGel: { id: 'slimeGel', name: 'Slime Gel', emoji: '💚', sellValue: 2 },
  wolfPelt: { id: 'wolfPelt', name: 'Wolf Pelt', emoji: '🟤', sellValue: 5 },
  fang: { id: 'fang', name: 'Fang', emoji: '🦷', sellValue: 3 },
  batWing: { id: 'batWing', name: 'Bat Wing', emoji: '🖤', sellValue: 4 },
  echoStone: { id: 'echoStone', name: 'Echo Stone', emoji: '💎', sellValue: 10 },
  goldCoin: { id: 'goldCoin', name: 'Gold Coin', emoji: '🪙', sellValue: 0 },
  // Fish
  small_fish: { id: 'small_fish', name: 'Small Fish', emoji: '🐟', sellValue: 3, category: 'fish' },
  large_fish: { id: 'large_fish', name: 'Large Fish', emoji: '🐠', sellValue: 7, category: 'fish' },
  river_crab: { id: 'river_crab', name: 'River Crab', emoji: '🦀', sellValue: 5, category: 'fish' },
  golden_carp: { id: 'golden_carp', name: 'Golden Carp', emoji: '✨', sellValue: 15, category: 'fish' },
  abyssal_eel: { id: 'abyssal_eel', name: 'Abyssal Eel', emoji: '🐍', sellValue: 12, category: 'fish' },
  old_boot: { id: 'old_boot', name: 'Old Boot', emoji: '👢', sellValue: 1, category: 'junk' },
  pearl_fragment: { id: 'pearl_fragment', name: 'Pearl Fragment', emoji: '🤍', sellValue: 8, category: 'gem' },
  crystal_shell: { id: 'crystal_shell', name: 'Crystal Shell', emoji: '🐚', sellValue: 10, category: 'gem' },
  sea_gem: { id: 'sea_gem', name: 'Sea Gem', emoji: '💠', sellValue: 20, category: 'gem' },
  ancient_coin: { id: 'ancient_coin', name: 'Ancient Coin', emoji: '🪙', sellValue: 0, category: 'special', goldValue: 25 },
  sunken_ring: { id: 'sunken_ring', name: 'Sunken Ring', emoji: '💍', sellValue: 18, category: 'gem' },
  // Ores
  copper_ore: { id: 'copper_ore', name: 'Copper Ore', emoji: '🟠', sellValue: 4, category: 'ore' },
  iron_ore: { id: 'iron_ore', name: 'Iron Ore', emoji: '⬜', sellValue: 8, category: 'ore' },
  crystal_ore: { id: 'crystal_ore', name: 'Crystal Ore', emoji: '🔷', sellValue: 14, category: 'ore' },
  rough_stone: { id: 'rough_stone', name: 'Rough Stone', emoji: '🪨', sellValue: 2, category: 'ore' },
  copper_nugget: { id: 'copper_nugget', name: 'Copper Nugget', emoji: '🟤', sellValue: 10, category: 'ore' },
  iron_nugget: { id: 'iron_nugget', name: 'Iron Nugget', emoji: '⚪', sellValue: 16, category: 'ore' },
  gemstone_shard: { id: 'gemstone_shard', name: 'Gemstone Shard', emoji: '💎', sellValue: 12, category: 'gem' },
  void_crystal: { id: 'void_crystal', name: 'Void Crystal', emoji: '🟣', sellValue: 25, category: 'gem' },
};
