export const MERCHANT_CONFIG = {
  spawnInterval: {
    min: 180000,
    max: 360000,
  },
  stayDuration: 60000,
  despawnWarning: 15000,
  spawnZones: [
    { zone: 'town',     weight: 10 },
    { zone: 'forest',   weight: 30 },
    { zone: 'caves',    weight: 20 },
    { zone: 'swamp',    weight: 25 },
    { zone: 'volcanic', weight: 15 },
  ],
  nightSpawnMultiplier: 1.5,
  textureKey: 'npc_merchant',
  nameColor: '#DAA520',
  speechBubble: true,
};

export const MERCHANT_INVENTORY_POOL = {
  guaranteed: [
    {
      id: 'merchant_mystery_seed',
      name: 'Mystery Seed',
      icon: '🌱',
      cost: 30,
      description: 'Plant it and see what grows. Could be any crop, including rare ones.',
      category: 'seed',
      maxQuantity: 3,
    },
  ],
  rotating: [
    {
      id: 'ember_pepper_seed',
      name: 'Ember Pepper Seed',
      icon: '🌶️',
      cost: 45,
      weight: 15,
      description: 'A volcanic crop. Grows in 60s. Used in fire-themed cooking recipes.',
      category: 'seed',
      maxQuantity: 5,
    },
    {
      id: 'frost_lily_seed',
      name: 'Frost Lily Seed',
      icon: '❄️',
      cost: 50,
      weight: 12,
      description: 'A delicate cave flower. Grows in 90s. Cooking ingredient for powerful frost buffs.',
      category: 'seed',
      maxQuantity: 3,
    },
    {
      id: 'golden_treat',
      name: 'Golden Treat',
      icon: '🦴',
      cost: 40,
      weight: 20,
      description: 'Feed to your companion. Doubles their perk effect for 3 minutes.',
      category: 'companion',
      maxQuantity: 2,
    },
    {
      id: 'merchants_tonic',
      name: "Merchant's Tonic",
      icon: '🧴',
      cost: 35,
      weight: 25,
      description: '+50% sell value on all items for 2 minutes.',
      category: 'food',
      maxQuantity: 2,
      buff: {
        id: 'merchants_tonic',
        name: "Merchant's Tonic",
        stats: {},
        skillEffects: { sellValueBonus: 0.50 },
        duration: 120000,
      },
    },
    {
      id: 'wanderers_brew',
      name: "Wanderer's Brew",
      icon: '🍶',
      cost: 50,
      weight: 15,
      description: '+20% movement speed for 3 minutes.',
      category: 'food',
      maxQuantity: 1,
      buff: {
        id: 'wanderers_brew',
        name: "Wanderer's Brew",
        stats: {},
        skillEffects: { moveSpeedBonus: 0.20 },
        duration: 180000,
      },
    },
    {
      id: 'scouts_map',
      name: "Scout's Map",
      icon: '🗺️',
      cost: 60,
      weight: 10,
      description: 'Reveals all mob positions on the minimap for 2 minutes.',
      category: 'consumable',
      maxQuantity: 1,
    },
    {
      id: 'agent_lantern',
      name: 'Lantern',
      icon: '🏮',
      cost: 75,
      weight: 8,
      description: 'Equip on agent to remove night morale debuff. Permanent until unequipped.',
      category: 'gear',
      slot: 'accessory',
      maxQuantity: 1,
      stats: { atk: 0, def: 2 },
      rarity: 'uncommon',
      perk: 'night_vision',
    },
    {
      id: 'agent_morale_scroll',
      name: 'Morale Scroll',
      icon: '📜',
      cost: 25,
      weight: 20,
      description: 'Removes agent night debuff for 5 minutes. Consumed on use.',
      category: 'consumable',
      maxQuantity: 3,
    },
    {
      id: 'stardust',
      name: 'Stardust',
      icon: '✨',
      cost: 100,
      weight: 5,
      description: 'Guarantees a rarity upgrade when used in gear enhancement. Very rare.',
      category: 'material',
      maxQuantity: 1,
    },
    {
      id: 'exotic_feast',
      name: 'Exotic Feast',
      icon: '🍱',
      cost: 80,
      weight: 8,
      description: '+10 ATK, +10 DEF, +25 Max HP for 180s. A meal from distant lands.',
      category: 'food',
      maxQuantity: 1,
      buff: {
        id: 'exotic_feast',
        name: 'Exotic Feast',
        stats: { atk: 10, def: 10, maxHp: 25 },
        skillEffects: {},
        duration: 180000,
      },
    },
  ],
};
